DROP TABLE IF EXISTS user_projects CASCADE;
DROP TABLE IF EXISTS project_hashtags CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS hashtags CASCADE;
DROP TABLE IF EXISTS users CASCADE;